# PyTorch Fundamentals

## 1. Matrices


### Matrices Brief Introduction
- Basic definition: rectangular array of numbers.
- Tensors (PyTorch)
- Ndarrays (NumPy)

**<center> 2 x 2 Matrix (R x C)</center>**

1 | 1
--- | ---
1 | 1

**<center> 2 x 3 Matrix </center>**

1 | 1 | 1
--- | ---| ---
1 | 1 | 1

### 1.1 Creating Matrices

In [4]:
import numpy as np

In [ ]:
# Creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [ ]:
# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [3]:
import torch

In [ ]:
# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

### 1.2 Create Matrices with Default Values

In [ ]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
np.random.rand(2, 2)

array([[0.08224829, 0.25466666],
       [0.01832574, 0.26418074]])

In [ ]:
torch.rand(2, 2)

tensor([[0.0373, 0.6257],
        [0.8227, 0.0819]])

### 1.3 Seeds for Reproducibility

In [ ]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [ ]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [ ]:
# No seed
np.random.rand(2, 2)

array([[0.40336084, 0.17131577],
       [0.71965082, 0.29610519]])

In [ ]:
# No seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [ ]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [ ]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [ ]:
# Torch No Seed
torch.rand(2, 2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [ ]:
# Torch No Seed
torch.rand(2, 2)

tensor([[0.4556, 0.6323],
        [0.3489, 0.4017]])

**Seed for GPU is different for now...**

In [ ]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

### 1.3 NumPy and Torch Bridge

### NumPy to Torch

In [ ]:
# Numpy array
np_array = np.ones((2, 2))

In [ ]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [ ]:
print(type(np_array))

<class 'numpy.ndarray'>


In [ ]:
# Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)

In [ ]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [ ]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [ ]:
# Data types matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

**The conversion supports:**
1. `double`
2. `float`
3. `int64`, `int32`, `uint8`

In [ ]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]])

In [ ]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [ ]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [ ]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [ ]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

**Summary**
<br />These things don't matter much now. But later when you see error messages that require these particular tensor types, refer to this guide!

| NumPy Array Type        | Torch Tensor Type           |
| :-------------: |:--------------:|
| int64     | LongTensor |
| int32     | IntegerTensor |
| uint8      | ByteTensor      |
| float64 | DoubleTensor     |
| float32 | FloatTensor      |
| double | DoubleTensor      |

### Torch to NumPy

In [ ]:
torch_tensor = torch.ones(2, 2)

In [ ]:
type(torch_tensor)

torch.Tensor

In [ ]:
torch_to_numpy = torch_tensor.numpy()

In [ ]:
type(torch_to_numpy)

numpy.ndarray

### 1.4 Tensors on CPU vs GPU

In [ ]:
# CPU
tensor_cpu = torch.ones(2, 2)

In [ ]:
# CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [ ]:
# GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

### 1.5 Tensor Operations

### Resizing Tensor

In [ ]:
a = torch.ones(2, 2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
print(a.size())

torch.Size([2, 2])


In [ ]:
a.view(4)

tensor([1., 1., 1., 1.])

In [ ]:
a.view(4).size()

torch.Size([4])

### Element-wise Addition

In [ ]:
a = torch.ones(2, 2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
b = torch.ones(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Element-wise addition
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [ ]:
# Element-wise addition
c = torch.add(a, b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [ ]:
# In-place addition
print('Old c tensor')
print(c)

c.add_(a)

print('-'*60)
print('New c tensor')
print(c)

Old c tensor
tensor([[2., 2.],
        [2., 2.]])
------------------------------------------------------------
New c tensor
tensor([[3., 3.],
        [3., 3.]])


### Element-wise Subtraction

In [ ]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
a - b

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
# Not in-place
print(a.sub(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Inplace
print(a.sub_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


### Element-Wise Multiplication

In [ ]:
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [ ]:
a * b

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
# Not in-place
print(torch.mul(a, b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# In-place
print(a.mul_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


### Element-Wise Division

In [ ]:
a = torch.ones(2, 2)
b = torch.zeros(2, 2)

In [ ]:
b / a

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.div(b, a)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
# Inplace
b.div_(a)

tensor([[0., 0.],
        [0., 0.]])

### Tensor Mean

- $1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55$
- $mean = 55 /10 = 5.5$


In [6]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [7]:
a.mean(dim=0)

tensor(5.5000)

In [12]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

In [9]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

In [10]:
a.size()

torch.Size([2, 10])

In [11]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

## Tensor Standard Deviation

In [ ]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)

---
# We've learnt to...
1. Create Matrices
2. Create Matrices with Default Initialization Values
    - Zeros
    - Ones
3. Initialize Seeds for Reproducibility on GPU and CPU
4. Convert Matrices: NumPy => Torch and Torch => NumPy
5. Move Tensors: CPU => GPU and GPU => CPU
6. Run Important Tensor Operations
    - Element-wise addition, subtraction, multiplication and division
    - Resize
    - Calculate mean
    - Calculate standard deviation